### ISSUE TITLE
Is this serious?

### ISSUE THREAD

**Issue by TaoismDeepLake** [lksj-dev/lksj-codex-zeitgeist#1]
Is this some kind of April Fool's joke or something? Such logs flood MC community's Q&A sections, it is just a pain to reformat them there.

**Comment by 3TUSK** [comment]
Yes, it is serious. 
Yes, it is pain to curate them, but the longer time we delay this, the more we will suffer next time we see the same thing coming again and again. 

> 不积跬步，无以至千里；不积小流，无以成江海；骐骥一跃，不能十步，驽马十驾，功在不舍；锲而舍之，朽木不折，锲而不舍，金石可镂。
> ——《荀子》卷第一
